### ISSUE TITLE
"Separate By Materials" Causes Normal-Related Operations to Fail

### ISSUE THREAD

**Issue by kafeijk** [MMD-Blender/blender_mmd_tools#269]
## Issue Description
In Blender 4.5 with mmd_tools 4.5, after executing "Separate By Materials," all operations related to normals fail to take effect.  
For example:  
- "Merge Vertices By Distance"  
- "Recalculate Normal"  
- "Weld Modifier"  
- "Shade Flat"  

<img width="1169" height="458" alt="Image" src="https://github.com/user-attachments/assets/8b0d18fe-68f6-4299-81fe-66c44ef2df72" />

None of these operations will modify the normals unless "Clear Custom Split Normals Data" is manually executed after performing "Separate By Materials."

## Environment
- Blender 4.5 + mmd_tools 4.5

**Comment by rintrint** [comment]
Should be fixed in 4c31a1c. Thank you.

Personally, I don’t recommend using `Separate By Materials`, just like I mentioned in the description. But since you can describe the issue precisely, perhaps you’re also well aware of the side effects.

**Comment by ulyssas** [comment]
I found on Blender 4.5 with latest MMD Tools, the `Data Transfer` modifer doesn't work for MMD models with `Separate By Materials`. Is this related to this issue?

**Comment by rintrint** [comment]
> I found on Blender 4.5 with latest MMD Tools, the `Data Transfer` modifer doesn't work for MMD models with `Separate By Materials`. Is this related to this issue?

Does this issue still occur with the new PR?"

**Comment by ulyssas** [comment]
It's still not working. The one in the middle in VRM model I imported for comparison, and that one is working. 

<img width="1415" height="796" alt="Image" src="https://github.com/user-attachments/assets/65911200-80b6-416a-a2d3-d6f3c117feb3" />

**Comment by rintrint** [comment]
Does this issue occur with the new PR in Blender versions earlier than 4.5?

**Comment by ulyssas** [comment]
No, it doesn't happen in Blender 4.2 with MMD Tools 4.5.0. I suspected Blender's the issue, but it's not because VRMs are fine

**Comment by rintrint** [comment]
So just to confirm, both Blender 4.2 with MMD Tools 4.5.0 and the new PR are working fine?

**Comment by ulyssas** [comment]
I only tested PR #272, but still it doesn't work on Blender 4.5.2, but it works on 4.2.

This is how it supposed to work (Blender 4.2)
<img width="1624" height="1056" alt="Image" src="https://github.com/user-attachments/assets/0b7e70a9-7c4a-4454-842c-1f0b287d8918" />

And this is how it looks in Blender 4.5 with #272. The normal doesn't change at all.
<img width="1624" height="1056" alt="Image" src="https://github.com/user-attachments/assets/41810ec4-48df-46fe-b26d-6c30aa2304ae" />

**Comment by rintrint** [comment]
Does this issue only happen after executing 'Separate By Materials'?

**Comment by ulyssas** [comment]
No, I thought the same, but in the above image, I didn't separate the model. It happens even without separating.

**Comment by ulyssas** [comment]
I tested v4.3.6 and v4.3.10 and they both worked.

**Comment by ulyssas** [comment]
Thank you! it looks like it's working now.

<img width="795" height="746" alt="Image" src="https://github.com/user-attachments/assets/f6525d9b-a33c-4678-8f41-b123965a6680" />

**Comment by rintrint** [comment]
OK. It seems that the mesh.attributes system in Blender 4.5 is still not mature enough. I might wait until Blender 5.0 or 6.0 before using it.

**Comment by ulyssas** [comment]
I confirmed all of the mentioned operations are functional even after separation.
> * "Merge Vertices By Distance"
> * "Recalculate Normal"
> * "Weld Modifier"
> * "Shade Flat"

And Data Transfer works before/after separation. Thank you for the fixes! I will close this issue.

**Comment by kafeijk** [comment]
Based on the  https://github.com/MMD-Blender/blender_mmd_tools/pull/272, exporting a model raises the exception  
`TypeError: cannot unpack non-iterable NoneType object`.  

<img width="1101" height="575" alt="Image" src="https://github.com/user-attachments/assets/7a91e761-3d9f-4d81-b116-2a15386ab33b" />

Environment  
blender4.5 + mmd_tools  https://github.com/MMD-Blender/blender_mmd_tools/pull/272

Reproduction Steps:  
1. Import a PMX model (the model must contain at least two UV maps).  

[test.zip](https://github.com/user-attachments/files/22189515/test.zip)

2. Execute "Separate By Materials".  
3. Perform "Merge Vertices By Distance" on any mesh object (with more than 1 vertex removed).  
4. Export the PMX model → error occurs.  

Additional Note:  
If the number of UV maps of the mesh object (that was merged by distance) is reduced to 1 before exporting, no error occurs.
This issue does not occur in blender4.5 + mmd_tools 4.3.9.

**Comment by rintrint** [comment]
I will be marking "Separate By Materials" as **HIGH RISK** (I'm even considering removing this feature entirely - I have no idea who added this to MMD Tools, it's causing nothing but harm).

"Separate By Materials" has never worked properly. All previous versions, including 4.3.9, have known issues. Attempts to fix existing problems inevitably create new ones - this is the sorry state of this broken feature.

Additionally, please **DO NOT export models that have been processed with "Separate By Materials"**. Keep your broken models in your own Blender workspace - do not export them and contaminate other workflows, as I've clearly stated in the "Separate By Materials" button description.

Regarding the issue you reported: this is yet another example of the fundamental problems with this feature. The TypeError during export after using "Separate By Materials" followed by "Merge Vertices By Distance" is just one of many cascading failures this feature causes. The fact that reducing UV maps to 1 prevents the error only demonstrates how fragile and unreliable this functionality is.

This reinforces my decision to mark it as high risk and potentially remove it altogether in future versions.

**Comment by ulyssas** [comment]
@kafeijk So Blender's built in separation fails as well?
One you can invoke in edit mode with `P`?

**Comment by rintrint** [comment]
Separate by Materials used to just rely on Blender's built-in separation, which is buggy.

**Comment by rintrint** [comment]
Fixed in 038e8d0. The messy mesh created by separating by materials and merging by distance accidentally revealed the exporter bug. Thanks.
